apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: thelounge-operator
  template:
    metadata:
      labels:
        name: thelounge-operator
    spec:
      serviceAccountName: thelounge-operator
      containers:
        - name: thelounge-operator
          # Replace this with the built image name
          image: quay.io/jcallen/thelounge-operator:debug
          command:
          - /usr/local/bin/dlv
          args:
          - "--listen=:40000"
          - "--headless=true"
          - "--api-version=2"
          - "--log"
          - "exec"
          - "/usr/local/bin/thelounge-operator"
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "thelounge-operator"
