// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.Thelounge":            schema_pkg_apis_the_v1alpha1_Thelounge(ref),
		"github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeSpec":        schema_pkg_apis_the_v1alpha1_TheloungeSpec(ref),
		"github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeStatus":      schema_pkg_apis_the_v1alpha1_TheloungeStatus(ref),
		"github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeUsers":       schema_pkg_apis_the_v1alpha1_TheloungeUsers(ref),
		"github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeUsersSpec":   schema_pkg_apis_the_v1alpha1_TheloungeUsersSpec(ref),
		"github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeUsersStatus": schema_pkg_apis_the_v1alpha1_TheloungeUsersStatus(ref),
	}
}

func schema_pkg_apis_the_v1alpha1_Thelounge(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Thelounge is the Schema for the thelounges API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeSpec", "github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_the_v1alpha1_TheloungeSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TheloungeSpec defines the desired state of Thelounge",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_the_v1alpha1_TheloungeStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TheloungeStatus defines the observed state of Thelounge",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_the_v1alpha1_TheloungeUsers(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TheloungeUsers is the Schema for the theloungeusers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeUsersSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeUsersStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeUsersSpec", "github.com/jcpowermac/thelounge-operator/pkg/apis/the/v1alpha1.TheloungeUsersStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_the_v1alpha1_TheloungeUsersSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TheloungeUsersSpec defines the desired state of TheloungeUsers",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_the_v1alpha1_TheloungeUsersStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TheloungeUsersStatus defines the observed state of TheloungeUsers",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
